base_url = "https://kmlupreti.xyz"
title = "Kamal Chandra Upreti"
description = "Kamal Chandra Upreti is a software developer from Nepal.He is interested in rust, linux, embedded systems and systems programming"#for SEO aim for 140-180 Characters
taxonomies = [{ name = "tags" }]
theme = "apollo"

[extra]
menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
  { name = "email", url = "mailto:kmlupreti@protonmail.com", icon = "email" },
  { name = "github", url = "https://github.com/kmlupreti", icon = "github" },
  { name = "linkedin", url = "https://www.linkedin.com/in/kmlupreti", icon = "linkedin" },
  { name = "facebook", url = "https://www.facebook.com/kmlupreti96/", icon = "facebook" },
  { name = "twitter", url = "https://x.com/kmlupreti96", icon = "x-twitter" },
  { name = "reddit", url = "https://www.reddit.com/user/kmlupreti96", icon = "reddit" },
  { name = "matrix", url = "https://matrix.to/#/@kmlupreti:matrix.org", icon = "matrix" },
  { name = "mastodon", url = "https://mastodon.social/@kmlupreti", icon = "mastodon" },
  ]

favicon = "avatar.png"
