# The base URL of the site; the only required configuration variable.
base_url = "https://kamalupreti.com.np"

# The site title and description; used in feeds by default.
title = "Kamal Chandra Upreti"
description = "Personal Blog site"

# The site theme to use.
theme = "anemone"

